### ISSUE TITLE
网易云外链无法显示

### ISSUE THREAD

**Issue by wielice** [muggledy/typora-dyzj-theme#1]
![image](https://user-images.githubusercontent.com/49556918/136128367-01508ac1-7972-4e86-a9ce-3c83ffd2cf3c.png)

首先，谢谢大佬这么棒的主题！
个人使用的时候发现只有网易云外链一片空白无法显示，不知为何？

![image](https://user-images.githubusercontent.com/49556918/136128511-a76bb029-9533-4235-a4e8-91de34251349.png)

**Comment by muggledy** [comment]
你好，请问你切换其他主题还存在该问题吗（我想这应该不是特定的主题样式所导致的），其次使用[官网](https://www.typora.net/328.html#embed-web-contents)的嵌入示例看看，如果其他网站的嵌入代码可以工作的话，那就到网易云重新复制嵌入代码，如果都不行的话，或许可以重新安装typora试试

**Comment by mxarcher** [comment]
@muggledy 请问这个问题解决了吗，我现在用的typora版本是1.1.5，依然无法显示网易的外链。
