### ISSUE TITLE
暗黑版样式

### ISSUE THREAD

**Issue by zybfsyqs** [muggledy/typora-dyzj-theme#10]
要是可以换个黑暗系的就好的，白的太耀眼了
![](https://i.bmp.ovh/imgs/2021/12/2f2feac933027d69.png)
![](https://i.bmp.ovh/imgs/2021/12/ce30387a3a5f7ad7.png)

下面这张是楼上改的，我也试了一下，可惜不太行
![image](https://user-images.githubusercontent.com/73592769/145953670-e07bcba7-701e-43f1-ae12-939db853ffe7.png)
我就想这只是把背景换成黑色或者紫色这种暗一点的
可惜楼上的把小风车啥的都去了

**Comment by muggledy** [comment]
你好，已增加暗黑样式：
![image](https://user-images.githubusercontent.com/26343222/146145565-0d61efaa-0625-40f4-a631-469695688838.png)

**Comment by zybfsyqs** [comment]
爱了爱了，作者

**Comment by zybfsyqs** [comment]
爱了爱了，作者
导出格式只有，好像那些样式就丢失了，只有html可以正常显示，pdf不行

**Comment by zybfsyqs** [comment]
爱了爱了，作者
导出格式只有，好像那些样式就丢失了，只有html可以正常显示，pdf不行

**Comment by muggledy** [comment]
当前版本不支持导出pdf时打印背景色，我看其他人主题也存在该问题:sweat_smile:：
![image](https://user-images.githubusercontent.com/26343222/146149281-05b5f7fb-281b-4bdc-a586-2d198c4a2b73.png)

**Comment by zybfsyqs** [comment]
确实，目前在typra里面看得挺好的，不过导出来就....，这也是一个需求吧，有时候需要导出来看

**Comment by muggledy** [comment]
有些动态样式确实不适用于pdf，https://files.catbox.moe/5iz1r9.pdf
导出为html的话还好，就是`<img>`下方的图释（自动编号）不能显示

**Comment by zybfsyqs** [comment]
亮色模式下基本没啥，暗黑模式就不行了
只不过亮色模式个人看的时候有点耀眼
可以写的时候用暗黑，导出用亮色
