### ISSUE TITLE
宝，代码块上下Mac主题的三个点

### ISSUE THREAD

**Issue by Ran-Xing** [muggledy/typora-dyzj-theme#14]

**Comment by ruyan-lx** [comment]
🎉宝，那三个点我加上了，可以试试我改的：[https://github.com/ruyan-lx/typora-dyzj-theme](https://github.com/ruyan-lx/typora-dyzj-theme)

**Comment by Ran-Xing** [comment]
@ruyan-lx 🐮🍺

**Comment by Ran-Xing** [comment]
@ruyan-lx 
[Windows Install OpenSSH.pdf](https://github.com/muggledy/typora-dyzj-theme/files/9867968/Windows.Install.OpenSSH.pdf)
[Windows Install OpenSSH2.pdf](https://github.com/muggledy/typora-dyzj-theme/files/9867969/Windows.Install.OpenSSH2.pdf)

好像不是很聪明的样子

---

## [生成密钥](https://docs.microsoft.com/zh-cn/azure/virtual-machines/linux/create-ssh-keys-detailed)

```powershell
ssh-keygen \
    -m PEM \
    -t rsa \
    -b 4096 \
    -C "laowang@qq.com" \
    -N my_ssh_passwd
```

## Install OpenSSH

```powershell
# >>>
Get-WindowsCapability -Online | Where-Object Name -like 'OpenSSH*'
```

```ini
<<<
Name  : OpenSSH.Client~~~~0.0.1.0
State : NotPresent

Name  : OpenSSH.Server~~~~0.0.1.0
State : NotPresent
```

```powershell
# >>>
# Install the OpenSSH Client
Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0

# Install the OpenSSH Server
Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
```

```ini
<<<
Path          :
Online        : True
RestartNeeded : False
```

```powershell
# >>>
# Start the sshd service
Start-Service sshd

# OPTIONAL but recommended:
Set-Service -Name sshd -StartupType 'Automatic'

# Confirm the Firewall rule is configured. It should be created automatically by setup. Run the following to verify
if (!(Get-NetFirewallRule -Name "OpenSSH-Server-In-TCP" -ErrorAction SilentlyContinue | Select-Object Name, Enabled)) {
    Write-Output "Firewall Rule 'OpenSSH-Server-In-TCP' does not exist, creating it..."
    New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -DisplayName 'OpenSSH Server (sshd)' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22
} else {
    Write-Output "Firewall rule 'OpenSSH-Server-In-TCP' has been created and exists."
}
```

## Uninstall OpenSSH

```powershell
# Uninstall the OpenSSH Client
Remove-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0

# Uninstall the OpenSSH Server
Remove-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
```

## [Configuration OpenSSH](https://docs.microsoft.com/zh-cn/windows-server/administration/openssh/openssh_server_configuration)

### Default Terminal

```powershell
New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -PropertyType String -Force
```

### File

- `C:\ProgramData\ssh\administrators_authorized_keys`
- `C:\ProgramData\ssh\sshd_config`
- `C:\Users\<UserName>\.ssh\authorized_keys`

### Config

- `StrictModes no`
- `PubkeyAuthentication yes`
- !!!     `PasswordAuthentication no`     !!!
- !!!     `PermiEmptyPasswords no`           !!!
- `AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys`

### Debug Model

```powershell
Stop-Service sshd
C:\Windows\System32\OpenSSH\sshd.exe -d
```

### Other

```powershell
Restart-Service sshd 	# 重启服务
Stop-Service sshd 		# 停止服务
Start-Service sshd		# 开启服务
```

**Comment by ruyan-lx** [comment]
😅😅😅因为设置了背景，不能导出为PDF。
要先将dyzj.css文件中背景图片注释
![image](https://user-images.githubusercontent.com/73696331/198008848-86f3ec85-cc75-4e6d-b1a2-933417f274f2.png)

**Comment by Ran-Xing** [comment]
@ruyan-lx 能不能把三个点放小一点，已关注

**Comment by ruyan-lx** [comment]
@Ran-Xing  改了一下

**Comment by Ran-Xing** [comment]
@ruyan-lx 大佬太强了

**Comment by ruyan-lx** [comment]
@Ran-Xing 😅没有没有，原作者才是强，我只是在巨人肩膀上改改皮毛

**Comment by Ran-Xing** [comment]
@ruyan-lx 
```bash
#write {
    /* max-width: 860px; 改动，整体显示宽度*/
	max-width: 1100px;
    /*margin: 100px auto;*/
    padding: 20px 30px 160px;
	/* 改动：新增文章主体背景颜色以及圆角 */
    background-color: #ffffffb0;
    border-radius: 10px;
	box-shadow: 0px 0px 20px 4px #ffffff;      
}
```

**Comment by Ran-Xing** [comment]
@ruyan-lx 我觉得顶部空间太多了

**Comment by ruyan-lx** [comment]
那就改成，`margin: 0px auto;` 
这是刚想到个高斯模糊的效果，想搭配背景图片去弄，所以顺手改大了些🙃

**Comment by Ran-Xing** [comment]
@ruyan-lx 你在你的仓库开启一下issues 权限，我蹭蹭你的
