### ISSUE TITLE
侧边文件树状列表的标题左边小箭头显示有问题

### ISSUE THREAD

**Issue by BYJRK** [muggledy/typora-dyzj-theme#2]
![image](https://user-images.githubusercontent.com/11771667/136649077-e1aeea07-bc2e-4648-beae-a6c146d8b079.png)

如上图，左侧的三角形展开和未展开两种同时存在。环境：Win 10，4K 200%

**Comment by muggledy** [comment]
感谢反馈，这个问题目前已解决

**Comment by CVNIWORE** [comment]
可以添加一个暗黑的样式，有干净白，也应当有优雅黑才好，白色长时间看，刺眼
