### ISSUE TITLE
小白，有个问题想要问下，

### ISSUE THREAD

**Issue by mazhenxin1998** [muggledy/typora-dyzj-theme#6]
![image](https://user-images.githubusercontent.com/56750847/141689433-b199f86e-15a0-4d8d-912a-4467f9dcd4d7.png)
这几个应该如何显示呢？ 找了好久没找到方法

**Comment by muggledy** [comment]
指的是主题的安装和使用吗？可以参考：https://theme.typora.io/doc/Install-Theme/

**Comment by ConnorTomato** [comment]
您好，我也不太明白小标签、以及彩虹字体等特效是如何使用的？

> 指的是主题的安装和使用吗？可以参考：https://theme.typora.io/doc/Install-Theme/

**Comment by muggledy** [comment]
第一步还是先按照上述链接正确安装主题。仓库里提供了一个“demo.md”文件，使用Typora打开并切换为Dyzj主题后，鼠标点击小标签等，就可以看到其写法，譬如红色小标签的写法为：`<font alt="red">文本内容</font>`、彩虹文本写法为：`<span alt="rainbow">彩虹字体</span>`

**Comment by ConnorTomato** [comment]
感谢您的回复，在查看"demo.md"的源码后，已清楚使用方法。

**Comment by haotangzhou** [comment]
请问有什么方法可以在typora里面给小标签和波浪线设置快捷键吗？Typora提供的快捷键设置方法好像只能设置内置的命令。

**Comment by muggledy** [comment]
这个做不到吧
