### ISSUE TITLE
代码块里输入 >= 结果变成 ≥ 了

### ISSUE THREAD

**Issue by luceln** [muggledy/typora-dyzj-theme#7]
![image](https://user-images.githubusercontent.com/62422565/142408896-0209e84b-ebb3-4415-9820-76d5c442d9a8.png)
小于等于也会变，typora 自带的GitHub主题没有这个问题

**Comment by muggledy** [comment]
你好，这是[*JetBrains Mono*](https://www.jetbrains.com/zh-cn/lp/mono/#ligatures)字体的特点，如果不期望这种行为，可以修改*dyzj.css*中的`--code-font`变量，如'KaiTi'等
