### ISSUE TITLE
二级标题、提示块标签无法正常显示图标

### ISSUE THREAD

**Issue by Sun-llq** [muggledy/typora-dyzj-theme#8]
如题，插入二级标题后，旋转特效正常但是小风车无显示变成了长方体，提示块一样，行内公式也无法正常显示
![image](https://user-images.githubusercontent.com/78143549/143802625-f75eab25-251d-442b-ac26-ff2ec5579630.png)
![image](https://user-images.githubusercontent.com/78143549/143802660-323b79e3-3f81-4555-8b67-c68f2940d00d.png)
![image](https://user-images.githubusercontent.com/78143549/143802757-f5018a12-0768-4f15-a95d-d615880f6821.png)

**Comment by muggledy** [comment]
1. 相关的图标样式源自`source/`文件夹，请问`source/`文件夹是否存在主题安装目录下呢（和dyzj.css同级）
2. 行内公式显示不出应该不是因为主题css的原因，可以切换至typora自带主题样式如github查看
3. 如果第1点没有问题的话，可以再详细说明一下环境吗，如操作系统，因为我只在windows上测试过

**Comment by Sun-llq** [comment]
> 1. 相关的图标样式同`source/`文件夹，请问那个文件夹`source/`是否存在主题安装目录下呢（和dyzj.css级）
> 2. 行内公式显示不出应该不是因为主题css的原因，可以切换到typora自带主题样式如github查看
> 3. 如果第1条没有问题的话，可以再详细说明一下环境吗，比如点什么，因为我只在windows上测试过

解决了，谢谢大佬，我的source/文件夹没有和dyzj.css级同级所以没办法识别，同级后就解决了。
行内公式的话，我切换到github主题样式查看，也不行
